.TH MEOWFETCH "1" "July 2022" "Meowfetch {VERSION}" "User Commands"

.SH NAME
meowfetch \- minimal, fast and customizable system information program written in go.

.SH SYNOPSIS
.B meowfetch
.RI [ ... OPTIONS ]

.SH DESCRIPTION
Meowfetch is a CLI system information tool written in go. meowfetch
displays information about your system next to an small cat.

.SH Command line Options
.TP
.B \-m\fR,\fB \-\-mode \fR[\fIpride, color\fR]
in pride flag background will mach the pride flag on each line. and
the value of color will be ignored. in color mode you can chose a color
for the ascii art. This value will be 4 by default but you can change it
from the config file or the command line arguments.

.TP
.B \-c\fR,\fB \-\-color \fR[\fI1..255\fR]
a number between 1 and 255 which overwrites the value of \fIcore.color\fR
at the runtime. Note that this value will be ignored if you set the
mode to pride mode.

.TP
.B \-b\fR,\fB \-\-border \fR{\fIround\fR,\fI single\fR,\fI double\fR,\fI none\fR}
this value will be over write the \fIcore.border_style\fR at the runtime.

.SH Configuration
Default configuration will be in the \fI$XDG_CONFIG_HOME/meowfetch/meow.conf\fR
if XDG_CONFIG_HOME was not set config will be generated at the user home
directory \fI$HOME/.meow.conf\fR program will ask you to create a
config at start otherwise it will use the default config.

.SH "LICENSE AND AUTHOR"
this progam is written and maintained by Itsnexn (https://github.com/itsnexn/meowfetch) and
licensed under MIT (https://opensource.org/licenses/MIT).

.SH "REPORTING BUGS"
Report bugs to https://github.com/itsnexn/meowfetch/issues
